spring:
  config:
    import: application-secret.yml

  output:
    ansi:
      enabled: always

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8080
  error:
    include-stacktrace: on_param
    include-exception: true